### PR TITLE
Disable mTLS for query frontend when gateway is disabled

### PR DESCRIPTION
**Pull request by rubenvp8510**
Fixes https://github.com/grafana/tempo-operator/issues/561

### CODE REVIEW

**Review by iblancasa — COMMENTED** [review]
Just asking because I don't know if it would make sense: do we want to test as part of the E2E tests what happens when the encryption feature flags are disabled? Or are we ok with just the unit tests?

**Review by pavolloffay — APPROVED** [review]

**Comment by rubenvp8510** [comment]
> Just asking because I don't know if it would make sense: do we want to test as part of the E2E tests what happens when the encryption feature flags are disabled? Or are we ok with just the unit tests?

I think is a good idea, but we need to figure out how to do it in the right way. I would say this could be a separate PR.

**Review by iblancasa — APPROVED** [review]

**Comment by rubenvp8510** [comment]
@andreasgerstmayr Fixed the openshift tests

```
--- PASS: kuttl (154.20s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/route (19.82s)
        --- PASS: kuttl/harness/multitenancy (125.48s)
        --- PASS: kuttl/harness/monitoring (144.18s)
        --- PASS: kuttl/harness/red-metrics (147.59s)

```

**Review by andreasgerstmayr — APPROVED** [review]

**Comment by rubenvp8510** [comment]
Any other thing required to merge this?

**Pull request merged**
