### PR TITLE
Update default operator namespaces

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
Update default operator namespaces

Default namespaces:
* manifests, Kubernetes: tempo-operator-system
* manifests, OpenShift: tempo-operator-system
* OLM, community: tempo-operator-system
* OLM, OpenShift: tempo-operator-system
* RHOSDT, OpenShift: openshift-tempo-operator

### CODE REVIEW

**Comment by pavolloffay** [comment]
I might be wrong, but I remember that we agreed to use operator specific namespace for OLM as well

**Comment by andreasgerstmayr** [comment]
Updated the suggested-namespace of both bundles.

**Comment by pavolloffay** [comment]
https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-subscribe.tsx#L580

Monitoring checkbox on OCP can be enabled only when the operator is deployed in a namespace that starts with `openshift`

**Review by rubenvp8510 — APPROVED** [review]

**Review by frzifus — COMMENTED** [review]
Just to clarify the outcome:

| Type | Namespace |
|--------|--------------------|
| olm Kubernetes Community | tempo-operator-system |
| olm OpenShift Community | tempo-operator-system |
| olm OpenShift Product | openshift-tempo-operator |

Thats what we want?

**Comment by andreasgerstmayr** [comment]
Yes.
Effectively: all community distributions in `tempo-operator-system`, and only the OpenShift Product in `openshift-tempo-operator`.

**Pull request merged**
