### PR TITLE
Fix infinite reconciliation when oauth-proxy is used

### LINKED ISSUE #1018: Oauth-proxy on OpenShift causes infinite reconciliation loop
```
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
spec:
  storage:
    secret:
      name: minio-test
      type: s3
  storageSize: 1Gi
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          type: route
EOF
```


```
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: simplestmono
spec:
  storage:
    traces:
      backend: s3 
      size: 3Gi 
      s3: 
        secret: minio-test
  jaegerui:
    enabled: true 
    route:
      enabled: true
EOF
```

The secret tempo-simplest-cookie-proxy keeps updating, only the resource version

```
~ » k get secret tempo-simplest-cookie-proxy -o yaml                                                                                                                                                                                                                                                                                   ploffay@fedora
apiVersion: v1
data:
  session_secret: SUpCS1RJbURWN3FNTGdwQW1qUG5YQT09
kind: Secret
metadata:
  creationTimestamp: "2024-08-27T14:06:28Z"
  labels:
    app.kubernetes.io/component: query-frontend-proxy
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: tempo-operator
    app.kubernetes.io/name: tempo
  name: tempo-simplest-cookie-proxy
  namespace: ploffay
  ownerReferences:
  - apiVersion: tempo.grafana.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TempoStack
    name: simplest
    uid: 139aeb6f-2397-4b1c-8d6a-48571d83fa22
  resourceVersion: "466146"
  uid: f1a51906-3158-47c9-a3e6-93529777b9ed
type: Opaque
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » k get secret tempo-simplest-cookie-proxy -o yaml                                                                                                                                                                                                                                                                                   ploffay@fedora
apiVersion: v1
data:
  session_secret: Q2IycVByZjU2WXcxR09MMC92UWJvdz09
kind: Secret
metadata:
  creationTimestamp: "2024-08-27T14:06:28Z"
  labels:
    app.kubernetes.io/component: query-frontend-proxy
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: tempo-operator
    app.kubernetes.io/name: tempo
  name: tempo-simplest-cookie-proxy
  namespace: ploffay
  ownerReferences:
  - apiVersion: tempo.grafana.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TempoStack
    name: simplest
    uid: 139aeb6f-2397-4b1c-8d6a-48571d83fa22
  resourceVersion: "466149"
  uid: f1a51906-3158-47c9-a3e6-93529777b9ed
type: Opaque
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~ » k get secret tempo-simplest-cookie-proxy -o yaml                                                                                                                                                                                                                                                                                   ploffay@fedora
apiVersion: v1
data:
  session_secret: ZmlQMStCaC9HQmRKYnE0b0ZkOSt0UT09
kind: Secret
metadata:
  creationTimestamp: "2024-08-27T14:06:28Z"
  labels:
    app.kubernetes.io/component: query-frontend-proxy
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: tempo-operator
    app.kubernetes.io/name: tempo
  name: tempo-simplest-cookie-proxy
  namespace: ploffay
  ownerReferences:
  - apiVersion: tempo.grafana.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TempoStack
    name: simplest
    uid: 139aeb6f-2397-4b1c-8d6a-48571d83fa22
  resourceVersion: "466160"
  uid: f1a51906-3158-47c9-a3e6-93529777b9ed
type: Opaque

```

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #1018 

See https://github.com/openshift/oauth-proxy?tab=readme-ov-file#other-configuration-flags 

Tested with 
```yaml
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: simplestmono
spec:
  jaegerui:
    enabled: true 
    route:
      enabled: true
  storage:
    traces:
      backend: s3 
      size: 3Gi 
      s3: 
        secret: minio-test
EOF

kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: simplest
spec:
  storage:
    secret:
      name: minio-test
      type: s3
  storageSize: 1Gi
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          type: route
EOF
```

### CODE REVIEW

**Review by andreasgerstmayr — APPROVED** [review]
fixing a bug by deleting more lines of code than adding are the best PRs :grinning: :+1:

**Review by andreasgerstmayr — COMMENTED** [review]
oh wait. what if the serviceaccount token changes, then all the cookies will be invalidated because the secret changed?

**Review by rubenvp8510 — APPROVED** [review]

**Comment by rubenvp8510** [comment]
> oh wait. what if the serviceaccount token changes, then all the cookies will be invalidated because the secret changed?

I'm assuming yes, how frecuent does the token changes?

**Review by iblancasa — APPROVED** [review]

**Comment by iblancasa** [comment]
> oh wait. what if the serviceaccount token changes, then all the cookies will be invalidated because the secret changed?

I would expect this to happen.

> I'm assuming yes, how frecuent does the token changes?

Since we are not setting `expirationSeconds`... I think the token will not expire. If the token changes is because the service account changed and it will be removed or something. In that case, that is not usual, I think it should be ok to just log out all the users.

What do you think @rubenvp8510 @andreasgerstmayr? If you agree, please, merge the PR. Thanks!

**Comment by rubenvp8510** [comment]
> > oh wait. what if the serviceaccount token changes, then all the cookies will be invalidated because the secret changed?
> 
> I would expect this to happen.
> 
> > I'm assuming yes, how frecuent does the token changes?
> 
> Since we are not setting `expirationSeconds`... I think the token will not expire. If the token changes is because the service account changed and it will be removed or something. In that case, that is not usual, I think it should be ok to just log out all the users.
> 
> What do you think @rubenvp8510 @andreasgerstmayr? If you agree, please, merge the PR. Thanks!

If that is the case (the token doesn't expire and change only if the service account is updated), I think is an acceptable behavior. On the other side, if the token is expiring for example each 60 seconds or so, then it will be really annoying for the users to have to login again.

**Comment by IshwarKanse** [comment]
@pavolloffay I tested the fix and it is working fine. I didn't see any reconciliation loop, the UI is not logging out and there are no significant increase in the metrics controller_runtime_reconcile_time_seconds_count{controller="tempostack"} controller_runtime_reconcile_time_seconds_count{controller="tempomonolithic"} I'll keep an eye during the release testing if I run into any issues.

**Review by iblancasa — APPROVED** [review]

**Pull request merged**
