### PR TITLE
[Chore] Test scale-up/scale-down of TempoStack components replica

### PR DESCRIPTION
**Pull request by IshwarKanse**
```
--- PASS: chainsaw (0.00s)
    --- PASS: chainsaw/component-replicas (224.28s)
PASS
Tests Summary...
- Passed  tests 1
- Failed  tests 0
- Skipped tests 0
Done.
```

### CODE REVIEW

**Review by iblancasa — APPROVED** [review]

**Review by rubenvp8510 — APPROVED** [review]

**Comment by andreasgerstmayr** [comment]
I re-run the failing action 3 times but it's always failing with
```
FAIL: chainsaw/monolithic-receivers-tls (207.08s)
```

It doesn't look directly related to this PR, but this test doesn't fail with other PRs :thinking:

**Comment by IshwarKanse** [comment]
@andreasgerstmayr That test has been flaky on upstream, it has failed with other PRs as well and passes after few retries. It always passed in OCP CI jobs. Resource issues ? I can move these tests to the e2e-openshift.

**Comment by andreasgerstmayr** [comment]
hm yeah I just saw it failing with another PR. I'd prefer fixing it upstream, I guess it's just a timeout.

**Comment by IshwarKanse** [comment]
@andreasgerstmayr Ok, I'll take a look in the morning for that failing one.

**Comment by andreasgerstmayr** [comment]
I gave it a try with #1005, let's see :)

**Pull request merged**
